// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZCxil1M0mui7XRvWe_FkD8afSvaE4yg',
    appId: '1:917138763935:web:418c5096d64e36f8f672aa',
    messagingSenderId: '917138763935',
    projectId: 'crm-machine-test',
    authDomain: 'crm-machine-test.firebaseapp.com',
    storageBucket: 'crm-machine-test.appspot.com',
    measurementId: 'G-LVYQK5BNMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdah1TF743hWzUmGMDZIRhqbWNz7mrml0',
    appId: '1:917138763935:android:10d6746c196bb660f672aa',
    messagingSenderId: '917138763935',
    projectId: 'crm-machine-test',
    storageBucket: 'crm-machine-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe5EcNXKIc8RE5Pln402TeXb6AYIjnL0Q',
    appId: '1:917138763935:ios:ba42dab5e51e861af672aa',
    messagingSenderId: '917138763935',
    projectId: 'crm-machine-test',
    storageBucket: 'crm-machine-test.appspot.com',
    iosBundleId: 'com.example.crmMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe5EcNXKIc8RE5Pln402TeXb6AYIjnL0Q',
    appId: '1:917138763935:ios:86448efc9d0f2baef672aa',
    messagingSenderId: '917138763935',
    projectId: 'crm-machine-test',
    storageBucket: 'crm-machine-test.appspot.com',
    iosBundleId: 'com.example.crmMachineTest.RunnerTests',
  );
}
